#!/bin/sh
source $(dirname $0)/panel_colors

PANEL_FIFO=/tmp/panel-fifo
if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

# clock
while true;
do
	echo "C$(printf '%b' "\uf017") $(date +'%H:%M')"
	sleep 5
done > "$PANEL_FIFO" &

# date
while true;
do
	echo "D$(printf '%b' "\uf073") $(date +'%e %b')"
	sleep 5
done > "$PANEL_FIFO" &

# while true;
# do
# 	TEMP=$(cat '/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input' | sed 's/.\{3\}$//')
# 	echo "P$(printf '%b' "\uf06d") $TEMP"
# 	sleep 3
# done > "$PANEL_FIFO" &
# battery

cat "$PANEL_FIFO" | $(dirname $0)/panel_bar | lemonbar -g 1914x25+3+3 -f "Terminesspowerline-9" -f "FontAwesome-8" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" & disown

wait
