#!/bin/zsh

# Autostart
compton -b --config ~/.config/compton.config
nitrogen --restore

# Screen Padding
bspc config top_padding         28
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config border_width        2
bspc config window_gap          3 

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5

~/.config/bspwm/panel/panel &
