#!/bin/zsh

# Autostart
urxvtd &
sxhkd -c ~/.config/bspwm/sxhkdrc &
setxkbmap se
libinput-gestures-setup start
#compton -b --config ~/.config/compton.conf

# Screen Padding
bspc config top_padding         26
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config border_width        2
bspc config window_gap          3

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# Mouse config
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# Window config
bspc rule -a Pavucontrol state=floating
bspc rule -a Steam state=floating
bspc rule -a Skype state=floating
bspc rule -a Thunar state=floating

bspc monitor eDP-1 -d 'term' 'web' 'code' 'desktop' 'etc'

~/.config/polybar/launch.sh top
